#!/bin/sh
#
# Profile file for Vintage Terminal

# run bash file
if [ "$SHELL" == "/bin/bash" ]; then
  . ~/.bashrc
fi

# nethack - disable colors (TODO)
export NETHACKOPTIONS="nocolor"

# other aliases
alias ls='ls --color -F'
